name: build

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/giyomoon/filestash
          tags: |
            type=raw,value={{sha}}
          flavor: |
            latest=${{ endsWith(github.ref, github.event.repository.default_branch) }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          push: true
          platforms: linux/arm64
          file: ./docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
